TariffApp/urls.py
from django.conf.urls import url

from TariffApp import views

urlpatterns = [
    url(r'^feeList/', views.feeList, name='feeList'),
    url(r'^getFee/', views.getFee, name='getFee'),
    url(r'^toModify/', views.toModify, name='toModify'),
    url(r'^modify/', views.modify, name='modify'),
    # 启用
    url(r'^startUp/', views.startUp, name='startUp'),
    # 增加页面
    url(r'^toAddFee/', views.toAddFee, name='toAddFee'),
    # 增加功能
    url(r'^addFee', views.addFee, name='addFee'),
    # 删除功能
    url(r'^deleteFee/', views.deleteFee, name='deleteFee'),
    # 详情信息页
    url(r'^detailFee/', views.detailFee, name='detailFee'),

    # 判断资费类型是否存在
    url(r'^type_is_exit/', views.type_is_exit),
    # # # 根据时长排序
    url(r'^orderByTime/', views.orderByTime, name='orderByTime'),
    # 根据基费用排序
    url(r'^orderByCost/', views.orderByCost, name='orderByCost'),
    # 根据单位费用排序
    url(r'^orderUnitCost/', views.orderUnitCost, name='orderUnitCost')
]

accountApp/urls.py
from django.conf.urls import url

from accountApp import views

urlpatterns =[
    url(r'^accountList/', views.accountList, name='accountList'),
    url(r'^account_add/', views.account_add, name='account_add'),
    url(r'^account_json/',views.AccountView.as_view()),
    # url(r'^account_json/',views.AccountView.as_view()),

    # 保存
    url(r'^account_save/',views.account_save),
   #状态
    url(r'^change_status/',views.change_status),
    #修改
    url(r'^account_modi/',views.account_modi),
    url(r'^account_detail/',views.account_detail,),

]

adminApp/urls.py
from django.conf.urls import url

from adminApp import views

urlpatterns =[
    url(r'^login/',views.login, name='login'),
    url(r'^checklogin/',views.checklogin,name='checklogin'),
    # 图片验证码
    url(r'^get_code/', views.get_code, name='get_code'),
    url(r'^home/', views.home),
]

netcotss/urls.py
b"""netcotss URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tariffApp/', include('TariffApp.urls', namespace='tariffApp')),
    url(r'^accountApp/', include('accountApp.urls', namespace='accountApp')),
    url(r'^serviceApp/', include('serviceApp.urls', namespace='serviceApp')),
    url(r'^adm/', include('adminApp.urls', namespace='adm'))
]

serviceApp/urls.py
from django.conf.urls import url

from serviceApp import views

urlpatterns = [
    # 展示所有数据库信息
    url(r'^serviceList/', views.serviceList, name='serviceList'),
    # 跳转到添加页面
    url(r'^toServiceAdd/', views.toServiceAdd, name='toServiceAdd'),
    # 添加功能实现
    url(r'^serviceAdd/', views.serviceAdd, name='serviceAdd'),
    # 跳转到修改页面
    url(r'^toServiceModi/', views.toServiceModi, name='toServiceModi'),
    # 修改功能实现
    url(r'^serviceModi/', views.serviceModi, name='serviceModi'),
    # 跳转到详情页面
    url(r'serviceDetial/', views.serviceDetial, name='serviceDetial'),
    # 添加页面，身份证信息查询
    url(r'^search_idCard/', views.serch_idCard, name='search_idCard'),
    # 判断是否保存成功,判断host下os账号是否已经存在
    url(r'^is_save_sure/', views.is_save_sure, name='is_save_sure'),
    # 删除功能实现
    url(r'^serviceDel/', views.serviceDel, name='serviceDel'),
    # 暂停和开通功能实现
    url(r'^serviceSet/', views.serviceSet, name='serviceSet'),
    # 联合查询
    url(r'^serviceSearch/', views.serviceSearch, name='serviceSearch')

]

templates/main/service/base_service.html
{% extends 'base.html' %}

{% load static %}
{% block ext_js %}
    {{ blcok.super }}
    <script type="text/javascript">

    </script>
{% endblock %}

{% block header %}
    {{ block.super }}
    <!--Logo区域开始-->
<div id="header">
    <img src="{% static 'images/log.png' %}" alt="logo" class="left"/>
    <span>当前账号：<b>action</b></span>
    <a href="{% url 'adm:login' %}">[退出]</a>
</div>
<!--Logo区域结束-->
    <!--导航区域开始-->
    <div id="navi">
        <ul id="menu">
            <li><a href="../index.html" class="index_off"></a></li>
            <li><a href="../role/role_list.html" class="role_off"></a></li>
            <li><a href="../admin/admin_list.html" class="admin_off"></a></li>
            <li><a href="{% url 'tariffApp:feeList' %}" class="fee_off"></a></li>
            <li><a href="{% url 'accountApp:accountList' %}" class="account_off"></a></li>
            <li><a href="{% url 'serviceApp:serviceList' %}" class="service_on"></a></li>
            <li><a href="../bill/bill_list.html" class="bill_off"></a></li>
            <li><a href="../report/report_list.html" class="report_off"></a></li>
            <li><a href="../user/user_info.html" class="information_off"></a></li>
            <li><a href="../user/user_modi_pwd.html" class="password_off"></a></li>
        </ul>
    </div>
    <!--导航区域结束-->
{% endblock %}

templates/main/service/service_add.html
{% extends 'main/service/base_service.html' %}

{% load static %}

{% block title %}
    {{ block.super }}

{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/service/js/service_add.js' %}"></script>

{% endblock %}

{% block content %}
    {{ block.super }}
    <!--主要区域开始-->
        <div id="main">
            <!--保存操作的提示信息-->
            <div id="save_result_info" class="save_fail"></div>
            <form action="{% url 'serviceApp:serviceAdd' %}" method="post" class="main_form" onsubmit="return parse()">
                <!--内容项-->
                <div class="text_info clearfix"><span>身份证：</span></div>
                <div class="input_info">
                    <input type="text" placeholder="查询出的结果写入账务账号" id="idcard_no" />
                    <input type="button" value="查询账务账号" class="btn_search_large" />
                    <span class="required">*</span>
                    <span class="validate_msg_short"></span>
                </div>
                <div class="text_info clearfix"><span>账务账号：</span></div>
                <div class="input_info">
                    <input type="text" value="" id="account_id" name="account_id" readonly="readonly"/>
                    <span class="required">*</span>
                    <span class="account_id_validate_msg"></span>
                </div>
                <div class="text_info clearfix"><span>资费类型：</span></div>
                <div class="input_info">
                    <select name="type">
                        <option value="包 20 小时">包 20 小时</option>
                        <option value="包 40 小时">包 40 小时</option>
                        <option value="包 60 小时">包 60 小时</option>
                        <option value="5.9元套餐">5.9元套餐</option>
                        <option value="6.9套餐">6.9套餐</option>
                        <option value="8.5元套餐">8.5元套餐</option>
                        <option value="10.5元套餐">10.5元套餐</option>
                        <option value="计时收费">计时收费</option>
                        <option value="包月">包月</option>
                    </select>
                </div>
                <div class="text_info clearfix"><span>服务器 IP：</span></div>
                <div class="input_info">
                    <input type="text" id="host" name="host"/>
                    <span class="required">*</span>
                    <span class="host_validate_msg"></span>
                </div>
                <div class="text_info clearfix"><span>登录 OS 账号：</span></div>
                <div class="input_info">
                    <input type="text" placeholder="创建即启用，状态为开通" id="os_name" name="os_name"/>
                    <span class="required">*</span>
                    <span class="os_name_validate_msg">8长度以内的字母、数字和下划线的组合</span>
                </div>
                <div class="text_info clearfix"><span>密码：</span></div>
                <div class="input_info">
                    <input type="password"  id="password" name="password"/>
                    <span class="required">*</span>
                    <span class="password_validate_msg_long">8-30长度以内的字母、数字和下划线的组合</span>
                </div>
                <div class="text_info clearfix"><span>重复密码：</span></div>
                <div class="input_info">
                    <input type="password"  id="password_sure"/>
                    <span class="required">*</span>
                    <span class="password_sure_validate_msg">两次密码必须相同</span>
                </div>
                <!--操作按钮-->
                <div class="button_info clearfix">
                    <input type="submit" value="保存" class="btn_save" id="service_save" disabled/>
                    <input type="button" value="取消" class="btn_save" id="addService_quit"/>
                </div>
            </form>
        </div>
        <!--主要区域结束-->

{% endblock %}

templates/main/service/service_detail.html
{% extends 'main/service/base_service.html' %}

{% load static %}

{% block title %}
    {{ block.super }}

{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/service/js/service_detial.js' %}"></script>
{% endblock %}

{% block content %}
    {{ block.super }}
    <!--主要区域开始-->
        <div id="main">
            <form action="" method="" class="main_form">
                <!--必填项-->
                <div class="text_info clearfix"><span>业务账号ID：</span></div>
                <div class="input_info"><input type="text" value={{ service.id }} readonly class="readonly" /></div>
                <div class="text_info clearfix"><span>账务账号ID：</span></div>
                <div class="input_info"><input type="text" value={{ service.s_account.id }} readonly class="readonly" /></div>
                <div class="text_info clearfix"><span>客户姓名：</span></div>
                <div class="input_info"><input type="text" readonly class="readonly" value={{ service.s_account.real_name }} /></div>
                <div class="text_info clearfix"><span>身份证号码：</span></div>
                <div class="input_info"><input type="text" readonly class="readonly" value={{ service.s_account.idcard_no }} /></div>
                <div class="text_info clearfix"><span>服务器 IP：</span></div>
                <div class="input_info"><input type="text" value={{ service.unix_host }} readonly class="readonly" /></div>
                <div class="text_info clearfix"><span>OS 账号：</span></div>
                <div class="input_info"><input type="text" value={{ service.os_username }} readonly class="readonly" /></div>
                <div class="text_info clearfix"><span>状态：</span></div>
                <div class="input_info">
                    <select disabled>
                        {% if service.status == True %}
                            <option>开通</option>
                            {% elif service.status == None %}
                            <option>删除</option>
                            {% else %}
                            <option>暂停</option>
                        {% endif %}
                    </select>
                </div>
                <div class="text_info clearfix"><span>开通时间：</span></div>
                <div class="input_info"><input type="text" readonly class="readonly" value="{{ service.create_date }}"/></div>
                <div class="text_info clearfix"><span>资费 ID：</span></div>
                <div class="input_info"><input type="text" class="readonly" readonly value="{{ service.s_usercost.id }}"/></div>
                <div class="text_info clearfix"><span>资费名称：</span></div>
                <div class="input_info"><input type="text" readonly class="width200 readonly" value="{{ service.s_usercost.name }}"/></div>
                <div class="text_info clearfix"><span>资费说明：</span></div>
                <div class="input_info_high">
                    <textarea class="width300 height70 readonly" readonly>{{ service.s_usercost.descr }}</textarea>
                </div>
                <!--操作按钮-->
                <div class="button_info clearfix">
                    <input type="button" value="返回" class="btn_save" id="detail_back"/>
                </div>
            </form>
        </div>
        <!--主要区域结束-->
{% endblock %}

templates/main/service/service_list.html
{% extends 'main/service/base_service.html' %}

{% load static %}

{% block title %}
    {{ block.super }}

{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/service/js/service_list.js' %}"></script>
{% endblock %}

{% block content %}
    {{ block.super }}
    <!--主要区域开始-->
        <div id="main">
            <form action="" method="">
                <!--查询-->
                <div class="search_add">
                    <div>OS 账号：<input type="text" value="" class="width100 text_search" id="os_name"/></div>
                    <div>服务器 IP：<input type="text" value="" class="width100 text_search" id="host"/></div>
                    <div>身份证：<input type="text"  value="" class="text_search" id="idcard_no"/></div>
                    <div>状态：
                        <select class="select_search" id="service_type">
                            <option>全部</option>
                            <option>开通</option>
                            <option>暂停</option>
                            <option>删除</option>
                        </select>
                    </div>
                    <div><input type="button" value="搜索" class="btn_search" id="search"/></div>
                    <input type="button" value="增加" class="btn_add" />
                </div>
                <!--删除的操作提示-->
                <div id="delete_result_info" class="delete_success">
                    <img src="{% static 'images/close.png' %}" onclick="this.parentNode.style.display='none';" />
                    删除成功！
                </div>

                <div id="pause_result_info" class="pause_success">
                    <img src="{% static 'images/close.png' %}" onclick="this.parentNode.style.display='none';" />
                    开通成功！
                </div>

                <div id="operate_result_info" class="operate_success">
                    <img src="{% static 'images/close.png' %}" onclick="this.parentNode.style.display='none';" />
                    暂停成功！
                </div>


                <!--数据区域：用表格展示数据-->
                <div id="data">
                    <table id="datalist">
                    <tr>
                        <th class="width50">业务ID</th>
                        <th class="width70">账务账号ID</th>
                        <th class="width150">身份证</th>
                        <th class="width70">姓名</th>
                        <th>OS 账号</th>
                        <th class="width50">状态</th>
                        <th class="width100">服务器 IP</th>
                        <th class="width100">资费</th>
                        <th class="width200"></th>
                    </tr>
                    {% for service in service_list %}
                    <tr>
                        <td><a href="{% url 'serviceApp:serviceDetial' %}?service_id={{ service.id }}" title="查看明细">{{ service.id }}</a></td>
                        <td>{{ service.s_account_id }}</td>
                        <td>{{ service.s_account.idcard_no }}</td>
                        <td>{{ service.s_account.real_name }}</td>
                        <td>{{ service.os_username }}</td>
                        {% if service.status %}
                            <td>开通</td>
                            {% elif service.status == None %}
                            <td>删除</td>
                            {% else %}
                            <td>暂停</td>
                        {% endif %}

                        <td>{{ service.unix_host }}</td>
                        <td>
                            <a class="summary"  onmouseover="showDetail(true,this);" onmouseout="showDetail(false,this);">{{ service.s_usercost.name }}</a>
                            <!--浮动的详细信息-->
                            <div class="detail_info">
                                20小时，24.5 元，超出部分 0.03元/分钟
                            </div>
                        </td>
                        <td class="td_modi">
                        {% if service.status == True %}

                            <input type="button" value="暂停" class="btn_pause" onclick="setState(this,{{ service.id }});" />
                            <input type="button" value="修改" class="btn_modify" onclick="modifi({{ service.id }})"/>
                            <input type="button" value="删除" class="btn_delete" onclick="deleteAccount({{ service.id }});" />
                            {% elif service.status == False %}
                            {% if service.s_account.status == False or service.s_account.status == None %}
                                <input type="button" value="开通" class="btn_pause"/>
                                {% else %}
                                <input type="button" value="开通" class="btn_pause" onclick="setState(this, {{ service.id }});" />
                            {% endif %}
                            <input type="button" value="修改" class="btn_modify" onclick="modifi({{ service.id }})"/>
                            <input type="button" value="删除" class="btn_delete" onclick="deleteAccount({{ service.id }});" />
                            {% else %}
                        {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

                </table>
                <p>业务说明：<br />
                1、创建即开通，记载创建时间；<br />
                2、暂停后，记载暂停时间；<br />
                3、重新开通后，删除暂停时间；<br />
                4、删除后，记载删除时间，标示为删除，不能再开通、修改、删除；<br />
                5、业务账号不设计修改密码功能，由用户自服务功能实现；<br />
                6、暂停和删除状态的账务账号下属的业务账号不能被开通。</p>
                </div>
                <!--分页-->
                <!--分页-->
                <div id="pages">
                    {% if service_list.has_previous %}
                        <a href="{% url 'serviceApp:serviceList' %}?page={{ service_list.previous_page_number }}">上一页</a>
                    {% else %}
                        <a href="#">上一页</a>
                    {% endif %}
                    {% for p in pages %}
                        {% if p == page %}
                            <a href="{% url 'serviceApp:serviceList' %}?page={{ p }}" style="color: red">{{ p }}</a>
                        {% else %}
                            <a href="{% url 'serviceApp:serviceList' %}?page={{ p }}">{{ p }}</a>
                        {% endif %}
                    {% endfor %}

                    {% if service_list.has_next %}
                        <a href="{% url 'serviceApp:serviceList' %}?page={{ service_list.next_page_number }}">下一页</a>
                    {% else %}
                        <a href="#">下一页</a>
                    {% endif %}

                </div>
            </form>
        </div>
        <!--主要区域结束-->
{% endblock %}

templates/main/service/service_modi.html
{% extends 'main/service/base_service.html' %}

{% load static %}

{% block title %}
    {{ block.super }}

{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/service/js/service_modi.js' %}"></script>
{% endblock %}

{% block content %}
    {{ block.super }}
    <!--主要区域开始-->
        <div id="main">
            <!--保存操作的提示信息-->
            <div id="save_result_info" class="save_fail"></div>
            <form action="{% url 'serviceApp:serviceModi' %}?service_id={{ service.id }}" method="" class="main_form">
                <!--必填项-->
                <div class="text_info clearfix"><span>业务账号ID：</span></div>
                <div class="input_info">
                    <input type="text" value="{{ service.id }}" readonly class="readonly" />
                </div>
                <div class="text_info clearfix"><span>OS 账号：</span></div>
                <div class="input_info">
                    <input type="text" value="{{ service.os_username }}" readonly class="readonly" name="os_name"/>
                </div>
                <div class="text_info clearfix"><span>服务器 IP：</span></div>
                <div class="input_info">
                    <input type="text" value="{{ service.unix_host }}" readonly class="readonly" name="host"/>
                </div>
                <div class="text_info clearfix"><span>资费类型：</span></div>
                <div class="input_info">
                    <select class="width150" name="cost_type">
                        <option value="包 20 小时">包 20 小时</option>
                        <option value="包 40 小时">包 40 小时</option>
                        <option value="包 60 小时">包 60 小时</option>
                        <option value="5.9元套餐">5.9元套餐</option>
                        <option value="6.9套餐">6.9套餐</option>
                        <option value="8.5元套餐">8.5元套餐</option>
                        <option value="10.5元套餐">10.5元套餐</option>
                        <option value="计时收费">计时收费</option>
                        <option value="包月">包月</option>
                    </select>
                    <div class="validate_msg_long">请修改资费类型，或者取消修改操作。</div>
                </div>
                <!--操作按钮-->
                <div class="button_info clearfix">
                    <input type="submit" value="保存" class="btn_save" />
                    <input type="button" value="取消" class="btn_save" onclick="cancel()"/>
                </div>


                <p>业务说明：<br />
                1、修改资费后，点击保存，并未真正修改数据库中的数据；<br />
                2、提交操作到消息队列；<br />
                3、每月月底由程序自动完成业务所关联的资费；</p>

            </form>
        </div>
        <!--主要区域结束-->
{% endblock %}