TariffApp/urls.py
from django.conf.urls import url

from TariffApp import views

urlpatterns = [
    url(r'^feeList/', views.feeList, name='feeList'),
    url(r'^getFee/', views.getFee, name='getFee'),
    url(r'^toModify/', views.toModify, name='toModify'),
    url(r'^modify/', views.modify, name='modify'),
    # 启用
    url(r'^startUp/', views.startUp, name='startUp'),
    # 增加页面
    url(r'^toAddFee/', views.toAddFee, name='toAddFee'),
    # 增加功能
    url(r'^addFee', views.addFee, name='addFee'),
    # 删除功能
    url(r'^deleteFee/', views.deleteFee, name='deleteFee'),
    # 详情信息页
    url(r'^detailFee/', views.detailFee, name='detailFee'),

    # 判断资费类型是否存在
    url(r'^type_is_exit/', views.type_is_exit),
    # # # 根据时长排序
    url(r'^orderByTime/', views.orderByTime, name='orderByTime'),
    # 根据基费用排序
    url(r'^orderByCost/', views.orderByCost, name='orderByCost'),
    # 根据单位费用排序
    url(r'^orderUnitCost/', views.orderUnitCost, name='orderUnitCost')
]

accountApp/urls.py
from django.conf.urls import url

from accountApp import views

urlpatterns =[
    url(r'^accountList/', views.accountList, name='accountList'),
    url(r'^account_add/', views.account_add, name='account_add'),
    url(r'^account_json/',views.AccountView.as_view()),
    # url(r'^account_json/',views.AccountView.as_view()),

    # 保存
    url(r'^account_save/',views.account_save),
   #状态
    url(r'^change_status/',views.change_status),
    #修改
    url(r'^account_modi/',views.account_modi),
    url(r'^account_detail/',views.account_detail,),

]

adminApp/urls.py
from django.conf.urls import url

from adminApp import views

urlpatterns =[
    url(r'^login/',views.login, name='login'),
    url(r'^checklogin/',views.checklogin,name='checklogin'),
    # 图片验证码
    url(r'^get_code/', views.get_code, name='get_code'),
    url(r'^home/', views.home),
]

netcotss/urls.py
b"""netcotss URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tariffApp/', include('TariffApp.urls', namespace='tariffApp')),
    url(r'^accountApp/', include('accountApp.urls', namespace='accountApp')),
    url(r'^serviceApp/', include('serviceApp.urls', namespace='serviceApp')),
    url(r'^adm/', include('adminApp.urls', namespace='adm'))
]

serviceApp/urls.py
from django.conf.urls import url

from serviceApp import views

urlpatterns = [
    # 展示所有数据库信息
    url(r'^serviceList/', views.serviceList, name='serviceList'),
    # 跳转到添加页面
    url(r'^toServiceAdd/', views.toServiceAdd, name='toServiceAdd'),
    # 添加功能实现
    url(r'^serviceAdd/', views.serviceAdd, name='serviceAdd'),
    # 跳转到修改页面
    url(r'^toServiceModi/', views.toServiceModi, name='toServiceModi'),
    # 修改功能实现
    url(r'^serviceModi/', views.serviceModi, name='serviceModi'),
    # 跳转到详情页面
    url(r'serviceDetial/', views.serviceDetial, name='serviceDetial'),
    # 添加页面，身份证信息查询
    url(r'^search_idCard/', views.serch_idCard, name='search_idCard'),
    # 判断是否保存成功,判断host下os账号是否已经存在
    url(r'^is_save_sure/', views.is_save_sure, name='is_save_sure'),
    # 删除功能实现
    url(r'^serviceDel/', views.serviceDel, name='serviceDel'),
    # 暂停和开通功能实现
    url(r'^serviceSet/', views.serviceSet, name='serviceSet'),
    # 联合查询
    url(r'^serviceSearch/', views.serviceSearch, name='serviceSearch')

]

templates/main/fee/base_fee.html
{% extends 'base.html' %}

{% load static %}
{% block ext_js %}
    {{ blcok.super }}
    <script type="text/javascript">

    </script>
{% endblock %}

{% block header %}
    {{ block.super }}
    <!--Logo区域开始-->
<div id="header">
    <img src="{% static 'images/log.png' %}" alt="logo" class="left"/>
    <span>当前账号：<b>action</b></span>
    <a href="{% url 'adm:login' %}">[退出]</a>
</div>
<!--Logo区域结束-->
    <!--导航区域开始-->
    <div id="navi">
        <ul id="menu">
            <li><a href="../index.html" class="index_off"></a></li>
            <li><a href="../role/role_list.html" class="role_off"></a></li>
            <li><a href="../admin/admin_list.html" class="admin_off"></a></li>
            <li><a href="{% url 'tariffApp:feeList' %}" class="fee_on"></a></li>
            <li><a href="{% url 'accountApp:accountList' %}" class="account_off"></a></li>
            <li><a href="{% url 'serviceApp:serviceList' %}" class="service_off"></a></li>
            <li><a href="../bill/bill_list.html" class="bill_off"></a></li>
            <li><a href="../report/report_list.html" class="report_off"></a></li>
            <li><a href="../user/user_info.html" class="information_off"></a></li>
            <li><a href="../user/user_modi_pwd.html" class="password_off"></a></li>
        </ul>
    </div>
    <!--导航区域结束-->
{% endblock %}

templates/main/fee/fee_add.html
{% extends 'main/fee/base_fee.html' %}

{% load static %}

{% block title %}
    {{ block.super }}
    添加套餐
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/fee/js/fee_add.js' %}"></script>

{% endblock %}

{% block content %}
    {{ block.super }}
    <!--主要区域开始-->
        <div id="main">
            <div id="save_result_info" class="save_fail"></div>
            <form action="{% url 'tariffApp:addFee' %}" method="post" class="main_form" onsubmit="return parse1()">
                <div class="text_info clearfix"><span>资费名称：</span></div>
                <div class="input_info">
                    <input type="text" class="width300" value="" name="name" id="cost_name"/>
                    <span class="required">*</span>
                    <div class="validate_msg_short" id="cost_validate_msg_short"></div>
                </div>
                <div class="text_info clearfix"><span>资费类型：</span></div>
                <div class="input_info fee_type">
                    <input type="radio" name="radFeeType" id="monthly" onclick="feeTypeChange(1);" value="包月"/>
                    <label for="monthly">包月</label>
                    <input type="radio" name="radFeeType" checked="checked" id="package" onclick="feeTypeChange(2);" value="套餐"/>
                    <label for="package">套餐</label>
                    <input type="radio" name="radFeeType" id="timeBased" onclick="feeTypeChange(3);" value="计时"/>
                    <label for="timeBased">计时</label>
                </div>
                <div class="text_info clearfix"><span>基本时长：</span></div>
                <div class="input_info">
                    <input type="text" value="" class="width100" name="bast_duration" id="bast_duration"/>
                    <span class="info">小时</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long">1-600之间的整数</div>
                </div>
                <div class="text_info clearfix"><span>基本费用：</span></div>
                <div class="input_info">
                    <input type="text" value="" class="width100" name="base_cost" id="base_cost"/>
                    <span class="info">元</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long error_msg">0-99999.99之间的数值</div>
                </div>
                <div class="text_info clearfix"><span>单位费用：</span></div>
                <div class="input_info">
                    <input type="text" value="" class="width100" name="unit_cost" id="unit_cost"/>
                    <span class="info">元/小时</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long error_msg">0-99999.99之间的数值</div>
                </div>
                <div class="text_info clearfix"><span>资费说明：</span></div>
                <div class="input_info_high">
                    <textarea class="width300 height70" name="descr" id="descr"></textarea>
                    <div class="validate_msg_short error_msg">100长度的字母、数字、汉字和下划线的组合</div>
                </div>
                <div class="button_info clearfix">
                    <input type="submit" value="保存" class="btn_save" />
                    <input type="button" value="取消" class="btn_save" id="fee_add_back"/>
                </div>
            </form>
        </div>
{% endblock %}

templates/main/fee/fee_detail.html
{% extends 'main/fee/base_fee.html' %}

{% load static %}

{% block title %}
    {{ block.super }}
    详情页面
{% endblock %}

{% block content %}
    {{ block.super }}
    <!--主要区域开始-->
        <div id="main">
            <form action="" method="" class="main_form">
                <div class="text_info clearfix"><span>资费ID：</span></div>
                <div class="input_info"><input type="text" class="readonly" readonly value="{{ cost.id }}" /></div>
                <div class="text_info clearfix"><span>资费名称：</span></div>
                <div class="input_info"><input type="text" class="readonly" readonly value="{{ cost.name }}"/></div>
                <div class="text_info clearfix"><span>资费状态：</span></div>
                <div class="input_info">
                    <select class="readonly" disabled>
                        {% if cost.status %}
                        <option>开通</option>
                        {% else %}
                        <option>暂停</option>

                        {% endif %}
                    </select>
                </div>
                <div class="text_info clearfix"><span>资费类型：</span></div>
                <div class="input_info fee_type">
                    {% if cost.name == '包月' %}
                    <input type="radio" name="radFeeType" id="monthly" disabled="disabled" checked/>
                    <label for="monthly">包月</label>
                    <input type="radio" name="radFeeType" id="timeBased" disabled="disabled" />
                    <label for="timeBased">计时</label>
                    <input type="radio" name="radFeeType" id="package" disabled="disabled" />
                    <label for="package">套餐</label>
                    {% elif cost.name == '计时' %}
                    <input type="radio" name="radFeeType" id="monthly" disabled="disabled" />
                    <label for="monthly">包月</label>
                    <input type="radio" name="radFeeType" checked="checked" id="timeBased" disabled="disabled" />
                    <label for="timeBased">计时</label>
                    <input type="radio" name="radFeeType" id="package" disabled="disabled" />
                    <label for="package">套餐</label>
                    {% else %}
                    <input type="radio" name="radFeeType" id="monthly" disabled="disabled" />
                    <label for="monthly">包月</label>
                    <input type="radio" name="radFeeType" id="timeBased" disabled="disabled" />
                    <label for="timeBased">计时</label>
                    <input type="radio" name="radFeeType" id="package" disabled="disabled" checked/>
                    <label for="package">套餐</label>
                    {% endif %}

                </div>
                <div class="text_info clearfix"><span>基本时长：</span></div>
                <div class="input_info">
                    <input type="text" class="readonly" readonly value="{{ cost.base_duration }}"  />
                    <span>小时</span>
                </div>
                <div class="text_info clearfix"><span>基本费用：</span></div>
                <div class="input_info">
                    <input type="text"  class="readonly" readonly value="{{ cost.base_cost }}" />
                    <span>元</span>
                </div>
                <div class="text_info clearfix"><span>单位费用：</span></div>
                <div class="input_info">
                    <input type="text"  class="readonly" readonly value="{{ cost.unit_cost }}" />
                    <span>元/小时</span>
                </div>
                <div class="text_info clearfix"><span>创建时间：</span></div>
                <div class="input_info"><input type="text"  class="readonly" readonly value="{{ cost.creatime }}" /></div>
                <div class="text_info clearfix"><span>启动时间：</span></div>
                <div class="input_info"><input type="text"  class="readonly" readonly value="{{ cost.startime }}" /></div>
                <div class="text_info clearfix"><span>资费说明：</span></div>
                <div class="input_info_high">
                    <textarea class="width300 height70 readonly" readonly>{{ cost.descr }}</textarea>
                </div>
                <div class="button_info clearfix">
                    <input type="button" value="返回" class="btn_save" onclick="location.href='{% url 'tariffApp:feeList' %}';" />
                </div>
            </form>
        </div>
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/fee/js/fee_modi.js' %}"></script>
{% endblock %}

templates/main/fee/fee_list.html
{% extends 'main/fee/base_fee.html' %}

{% load static %}

{% block title %}
    {{ block.super }}
    资费管理
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/js/menu.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/fee/js/fee_list.js' %}"></script>
{% endblock %}

{% block content %}
    {{ block.super }}

    <!--主要区域开始-->
    <div id="main">
        <form action="" method="">
            <!--排序-->
            <div class="search_add">
                <div>
{#                    <input type="button" value="单费" class="{{ order_unitCost }}"#}
{#                           onclick="sort(this,{{ page }}, this.value);"/>#}
{#                    <input type="button" value="基费" class="{{ order_baseCost }}"#}
{#                           onclick="sort(this,{{ page }}, this.value);"/>#}
{#                    <input type="button" value="时长" class="{{ order_time }}" onclick="sort(this,{{ page }}, this.value);"/>#}
                    <input type="button" value="单费" class="{{ order_unitCost }}" id="unit_cost_sort"/>
                    <input type="button" value="基费" class="{{ order_baseCost }}" id="cost_sort"/>
                    <input type="button" value="时长" class="{{ order_time }}" id="time_sort"/>
                </div>
                <input type="button" value="增加" class="btn_add" onclick="location.href='{% url 'tariffApp:toAddFee' %}'"/>
            </div>
            <!--启用操作的操作提示-->
            <div id="operate_result_info" class="operate_success">
                <img src="{% static 'images/close.png' %}" onclick="this.parentNode.style.display='none';"/>
                开通成功！
            </div>
            <!--启用操作的操作提示-->
            <div id="delete_result_info" class="delete_success" style="display: none">
                <img src="{% static 'images/close.png' %}" onclick="this.parentNode.style.display='none';"/>
                删除成功！
            </div>
            <!--数据区域：用表格展示数据-->
            <div id="data">
                <table id="datalist">
                    <tr>
                        <th>资费ID</th>
                        <th class="width100">资费名称</th>
                        <th>基本时长</th>
                        <th>基本费用</th>
                        <th>单位费用</th>
                        <th>创建时间</th>
                        <th>开通时间</th>
                        <th class="width50">状态</th>
                        <th class="width200"></th>
                    </tr>
                    {% for cost in costs %}
                        <tr>
                            <td>{{ cost.id }}</td>
                            <td><a href="{% url 'tariffApp:detailFee' %}?id={{ cost.id }}">{{ cost.name }}</a></td>
                            <td>{{ cost.base_duration }}</td>
                            <td>{{ cost.base_cost }}</td>
                            <td>{{ cost.unit_cost }}</td>
                            <td>{{ cost.creatime }}</td>
                            <td>{{ cost.startime }}</td>
                            {% if cost.status %}
                                <td>开通</td>
                            {% else %}
                                <td>暂停</td>
                            {% endif %}
                            <td>
                                {% if not cost.status %}
                                    <input type="button" value="启用" class="btn_start" onclick="startFee({{ cost.id }});"/>
                                    <input type="button" value="修改" class="btn_modify" onclick="location.href='{% url 'tariffApp:toModify' %}?id={{ cost.id }}';"/>
                                    <input type="button" value="删除" class="btn_delete" onclick="deleteFee({{ cost.id }});"/>
                                {% endif %}

                            </td>
                        </tr>
                    {% endfor %}
                </table>
                <p>业务说明：<br/>
                    1、创建资费时，状态为暂停，记载创建时间；<br/>
                    2、暂停状态下，可修改，可删除；<br/>
                    3、开通后，记载开通时间，且开通后不能修改、不能再停用、也不能删除；<br/>
                    4、业务账号修改资费时，在下月底统一触发，修改其关联的资费ID（此触发动作由程序处理）
                </p>
            </div>
            <!--分页-->
            <div id="pages">
                {% if costs.has_previous %}
                    <a href="{% url 'tariffApp:feeList' %}?page={{ costs.previous_page_number }}">上一页</a>
                {% else %}
                    <a href="#">上一页</a>
                {% endif %}
                {% for p in pages %}
                    {% if p == page %}
                        <a href="{% url 'tariffApp:feeList' %}?page={{ p }}" style="color: red">{{ p }}</a>
                    {% else %}
                        <a href="{% url 'tariffApp:feeList' %}?page={{ p }}">{{ p }}</a>
                    {% endif %}
                {% endfor %}

                {% if costs.has_next %}
                    <a href="{% url 'tariffApp:feeList' %}?page={{ costs.next_page_number }}">下一页</a>
                {% else %}
                    <a href="#">下一页</a>
                {% endif %}

            </div>
        </form>
    </div>

{% endblock %}

templates/main/fee/fee_modi.html
{% extends 'main/fee/base_fee.html' %}

{% load static %}

{% block title %}
    {{ block.super }}
    添加资费
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'main/fee/js/fee_modi.js' %}"></script>
{% endblock %}

{% block content %}
    {{ block.super }}
    <!--主要区域开始-->
        <div id="main">

            <form action="{% url 'tariffApp:modify' %}" method="post" class="main_form" onsubmit="return parse2()">
                <div class="text_info clearfix"><span>资费ID：</span></div>
                <div class="input_info"><input type="text" class="readonly" readonly value="{{ id }}" name="id"/></div>
                <div class="text_info clearfix"><span>资费名称：</span></div>
                <div class="input_info">
                    <input type="text" class="width300" value="包 20 小时" name="name" id="cost_name"/>
                    <span class="required">*</span>
                    <div class="validate_msg_short">如果是套餐则进行填写,否则不写</div>
                </div>
                <div class="text_info clearfix"><span>资费类型：</span></div>
                <div class="input_info fee_type">
                    <input type="radio" name="radFeeType" id="monthly" onclick="feeTypeChange(1);" value="包月"/>
                    <label for="monthly">包月</label>
                    <input type="radio" name="radFeeType" checked="checked" id="package" onclick="feeTypeChange(2);" value="套餐"/>
                    <label for="package">套餐</label>
                    <input type="radio" name="radFeeType" id="timeBased" onclick="feeTypeChange(3);" value="计时"/>
                    <label for="timeBased">计时</label>
                </div>
                <div class="text_info clearfix"><span>基本时长：</span></div>
                <div class="input_info">
                    <input type="text" value="" class="width100" name="base_duration" id="bast_duration"/>
                    <span class="info">小时</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long">1-600之间的整数</div>
                </div>
                <div class="text_info clearfix"><span>基本费用：</span></div>
                <div class="input_info">
                    <input type="text" value="" class="width100" name="base_cost" id="base_cost"/>
                    <span class="info">元</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long">0-99999.99之间的数值</div>
                </div>
                <div class="text_info clearfix"><span>单位费用：</span></div>
                <div class="input_info">
                    <input type="text" value="" class="width100" name="unit_cost" id="unit_cost"/>
                    <span class="info">元/小时</span>
                    <span class="required">*</span>
                    <div class="validate_msg_long">0-99999.99之间的数值</div>
                </div>
                <div class="text_info clearfix"><span>资费说明：</span></div>
                <div class="input_info_high">
                    <textarea class="width300 height70" name="descr" id="descr">没有启用的资费，可以修改除 ID 以外的所有信息
                    </textarea>
                    <div class="validate_msg_short">100长度的字母、数字、汉字和下划线的组合</div>
                </div>
                <div class="button_info clearfix">
                    <input type="submit" value="保存" class="btn_save" />
                    <input type="button" value="取消" class="btn_save" id="fee_modi_back"/>
                </div>
            </form>
        </div>
{% endblock %}
